version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: 'golesson'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/golesson/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgres://admin:postgres@db:5432/golesson?sslmode=disable
      SERVER_PORT: $SERVER_PORT
      READ_TIMEOUT: $READ_TIMEOUT
      WRITE_TIMEOUT: $WRITE_TIMEOUT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    restart: unless-stopped
    depends_on:
      - db  
volumes:
  postgres-db-volume:
